In [10]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv(
    "raw data/Amazon Sale Report.csv",
    low_memory=False
)

df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [ ]:
df.shape

(128975, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [ ]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [ ]:
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'Gujarat', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'Goa', 'MEGHALAYA', 'GOA',
       'TRIPURA', 'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', 'Delhi', nan,
       'ANDAMAN & NICOBAR ', 'Punjab', 'Rajshthan', 'Manipur',
       'rajasthan', 'Odisha', 'NL', 'Bihar', 'MIZORAM', 'punjab',
       'New Delhi', 'Rajasthan', 'Punjab/Mohali/Zirakpur', 'Puducherry',
       'delhi', 'RJ', 'Chandigarh', 'orissa', 'LAKSHADWEEP', 'goa', 'PB',
       'APO', 'Arunachal Pradesh', 'AR', 'Pondicherry', 'Sikkim',
       'Arunachal pradesh', 'Nagaland', 'bihar', 'Mizoram', 'rajsthan',
       'Orissa', 'Rajsthan', 'Meghalaya'], dtype=object)

In [ ]:
df['ship-state'] = (
    df['ship-state']
    .str.upper()
    .str.strip()
)

In [ ]:
df['ship-state'].unique()

array(['MAHARASHTRA', 'KARNATAKA', 'PUDUCHERRY', 'TAMIL NADU',
       'UTTAR PRADESH', 'CHANDIGARH', 'TELANGANA', 'ANDHRA PRADESH',
       'RAJASTHAN', 'DELHI', 'HARYANA', 'ASSAM', 'JHARKHAND',
       'CHHATTISGARH', 'ODISHA', 'KERALA', 'MADHYA PRADESH',
       'WEST BENGAL', 'NAGALAND', 'GUJARAT', 'UTTARAKHAND', 'BIHAR',
       'JAMMU & KASHMIR', 'PUNJAB', 'HIMACHAL PRADESH',
       'ARUNACHAL PRADESH', 'MANIPUR', 'GOA', 'MEGHALAYA', 'TRIPURA',
       'LADAKH', 'DADRA AND NAGAR', 'SIKKIM', nan, 'ANDAMAN & NICOBAR',
       'RAJSHTHAN', 'NL', 'MIZORAM', 'NEW DELHI',
       'PUNJAB/MOHALI/ZIRAKPUR', 'RJ', 'ORISSA', 'LAKSHADWEEP', 'PB',
       'APO', 'AR', 'PONDICHERRY', 'RAJSTHAN'], dtype=object)

In [ ]:
state_mapping = {
    'ORISSA':'ODISHA',
    'PONDICHERRY':'PUDUCHERRY',
    'NEW DELHI':'DELHI',
    'GOA':'GOA',
    'RAJASTHAN':'RAJASTHAN',
    'PUNJAB/MOHALI/ZIRAKPUR':'PUNJAB',
    'PB':'PUNJAB',
    'AR':'ARUNACHAL PRADESH',
    'APO':'ARUNACHAL PRADESH'
}

df['ship-state'] = df['ship-state'].replace(state_mapping)

In [ ]:
sorted(df['ship-state'].dropna().unique())

['ANDAMAN & NICOBAR',
 'ANDHRA PRADESH',
 'ARUNACHAL PRADESH',
 'ASSAM',
 'BIHAR',
 'CHANDIGARH',
 'CHHATTISGARH',
 'DADRA AND NAGAR',
 'DELHI',
 'GOA',
 'GUJARAT',
 'HARYANA',
 'HIMACHAL PRADESH',
 'JAMMU & KASHMIR',
 'JHARKHAND',
 'KARNATAKA',
 'KERALA',
 'LADAKH',
 'LAKSHADWEEP',
 'MADHYA PRADESH',
 'MAHARASHTRA',
 'MANIPUR',
 'MEGHALAYA',
 'MIZORAM',
 'NAGALAND',
 'NL',
 'ODISHA',
 'PUDUCHERRY',
 'PUNJAB',
 'RAJASTHAN',
 'RAJSHTHAN',
 'RAJSTHAN',
 'RJ',
 'SIKKIM',
 'TAMIL NADU',
 'TELANGANA',
 'TRIPURA',
 'UTTAR PRADESH',
 'UTTARAKHAND',
 'WEST BENGAL']

In [ ]:
df.drop(
    columns=['promotion-ids', 'fulfilled-by', 'Unnamed: 22'],
    inplace=True
)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

In [ ]:
df['Month'] = df['Date'].dt.month_name()

In [ ]:
df['Month'].unique()

array(['April', 'March', 'May', 'June'], dtype=object)

In [ ]:
import numpy as np

In [ ]:
df['Net_Revenue'] = np.where(
    df['Status'].str.upper() == 'CANCELLED',
    0,
    df['Amount']
)

In [ ]:
df[['Status','Amount','Net_Revenue']].head(20)

                          Status  Amount  Net_Revenue
0                      Cancelled  647.62          0.0
1   Shipped - Delivered to Buyer  406.00        406.0
2                        Shipped  329.00        329.0
3                      Cancelled  753.33          0.0
4                        Shipped  574.00        574.0
5                        Shipped  824.00        824.0
6                        Shipped  653.00        653.0
7   Shipped - Delivered to Buyer  399.00        399.0
8                      Cancelled     NaN          0.0
9                        Shipped  363.00        363.0
10                       Shipped  685.00        685.0
11                       Shipped  364.00        364.0
12  Shipped - Delivered to Buyer  399.00        399.0
13                       Shipped  657.00        657.0
14  Shipped - Delivered to Buyer  771.00        771.0
15  Shipped - Delivered to Buyer  544.00        544.0
16                       Shipped  329.00        329.0
17                       Shipped  399.00        399.0
18  Shipped - Delivered to Buyer  458.00        458.0
19                       Shipped  886.00        886.0

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

index                    0
Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
SKU                      0
Category                 0
Size                     0
ASIN                     0
Courier Status        6872
Qty                      0
currency              7795
Amount                7795
ship-city               33
ship-state              33
ship-postal-code        33
ship-country            33
B2B                      0
Month                    0
Net_Revenue            229
dtype: int64

In [ ]:
df.dropna(
    subset=['ship-city','ship-state','ship-postal-code','ship-country'],
    inplace=True
)

In [ ]:
df['Amount'] = df['Amount'].fillna(0)

In [ ]:
df['Net_Revenue'] = df['Net_Revenue'].fillna(0)

In [ ]:
df['currency'] = df['currency'].fillna('INR')

In [ ]:
df['Courier Status'] = df['Courier Status'].fillna('Unknown')

In [ ]:
df.isnull().sum()

index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
B2B                   0
Month                 0
Net_Revenue           0
dtype: int64

In [ ]:
df.to_csv('clean_amazon_sales.csv', index=False)

In [ ]:
sale_report = pd.read_csv("raw data/Sale Report.csv")

sale_report.columns

Index(['index', 'SKU Code', 'Design No.', 'Stock', 'Category', 'Size',
       'Color'],
      dtype='object')

In [ ]:
sale_report.head()

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

In [17]:
df['SKU'].head(10)

0         SET389-KR-NP-S
1        JNE3781-KR-XXXL
2          JNE3371-KR-XL
3             J0341-DR-L
4        JNE3671-TU-XXXL
5        SET264-KR-NP-XL
6            J0095-SET-L
7           JNE3405-KR-S
8    SET200-KR-NP-A-XXXL
9         JNE3461-KR-XXL
Name: SKU, dtype: object

In [18]:
sale_report['SKU Code'].head(10)

0         AN201-RED-L
1         AN201-RED-M
2         AN201-RED-S
3        AN201-RED-XL
4       AN201-RED-XXL
5      AN202-ORANGE-L
6      AN202-ORANGE-M
7      AN202-ORANGE-S
8     AN202-ORANGE-XL
9    AN202-ORANGE-XXL
Name: SKU Code, dtype: object

In [19]:
set(df['SKU']).intersection(
    set(sale_report['SKU Code'])
)

{'J0006-SET-M',
 'JNE3780-KR-XXXL',
 'J0095-SET-XXL',
 'JNE3334-KR-L',
 'MEN5008-KR-XL',
 'JNE3605-KR-S',
 'JNE3683-TU-S',
 'SET410-KR-NP-XS',
 'SET251-KR-PP-M',
 'SAR138',
 'JNE3363-KR-1032-S',
 'J0330-KR-L',
 'SET408-KR-NP-XL',
 'J0124-TP-M',
 'JNE1525-KR-UDF19BLACK-L',
 'BTM042-PP-XL',
 'MEN5001-KR-XL',
 'SET055-KR-NP-XXXL',
 'J0377-SKD-XL',
 'SET053-KR-NP-XS',
 'J0038-DR-XS',
 'SET223-KR-NP-XS',
 'JNE3674-TU-XL',
 'SET217-KR-PP-M',
 'SET396-KR-PP-XXXL',
 'SET319-KR-NP-S',
 'SET437-KR-PP-XXXL',
 'SET384-KR-NP-XXXL',
 'JNE3739-KR-XS',
 'J0152-DR-L',
 'J0333-DR-S',
 'SET316-KR-DPT-XS',
 'JNE3443-KR-XXL',
 'BTM030-NP-XXL',
 'JNE3735-KR-XL',
 'J0003-SET-L',
 'J0342-TP-XXXL',
 'JNE3766-KR-XXXL',
 'SET098-KR-PP-XL',
 'J0342-TP-S',
 'J0335-DR-XXL',
 'J0113-TP-XS',
 'SET253-KR-NP-M',
 'JNE3782-KR-XXL',
 'SET384-KR-NP-XL',
 'SET394-KR-NP-XXXL',
 'SET094-KR-NP-XXXL',
 'MEN5023-KR-XL',
 'JNE3667-TP-XL',
 'JNE3294-KR-XL',
 'SAR060',
 'JNE3471-KR-L',
 'SET308-KR-PP-XS',
 'JNE3531-KR-XL',
 'BTM033-NP-XXL',
 'JNE3865-TP-S',
 'SET083-KR-PP-L',
 'JNE3476-KR-S',
 'NW031-TP-PJ-XL',
 'NW027-TP-PJ-XXXL',
 'BL087-M',
 'JNE3775-KR-L',
 'JNE3445-KR-M',
 'SET351-KR-NP-M',
 'J0204-TP-S',
 'J0314-KR-XL',
 'SET386-KR-NP-XL',
 'JNE3741-KR-XXL',
 'J0172-TP-L',
 'J0144-SET-S',
 'JNE2171-KR-437-M',
 'PSET268-KR-NP-4XL',
 'JNE3431-KR-XXXL',
 'SET389-KR-NP-M',
 'J0037-KR-L',
 'JNE3702-KR-XXXL',
 'MEN5005-KR-XXXL',
 'JNE3680-TU-XXXL',
 'SET058-KR-NP-XXXL',
 'J0012-SKD-XXXL',
 'J0292-TP-XXXL',
 'J0396-DR-M',
 'JNE3606-KR-XL',
 'JNE3384-KR-XL',
 'J0281-SKD-XXL',
 'JNE3438-KR-XXXL',
 'J0314-KR-M',
 'J0090-TP-XL',
 'JNE3924-TU-XS',
 'NW015-TP-PJ-S',
 'JNE3753-KR-XXL',
 'SET366-KR-NP-S',
 'J0110-SKD-L',
 'SET384-KR-NP-M',
 'AN211-BLACK-S',
 'JNE3770-KR-XXXL',
 'MEN5001-KR-XXL',
 'SET377-KR-NP-XXL',
 'JNE3886-KR-L',
 'SET290-KR-DPT-S',
 'SET346-KR-PP-S',
 'SET147-KR-NP-XXXL',
 'SAR025',
 'JNE3431-KR-M',
 'SET377-KR-NP-XXXL',
 'JNE3654-TP-L',
 'J0023-TP-XXL',
 'JNE3716-KR-L',
 'J0172-TP-XXL',
 'J0181-TP-S',
 'NW035-ST-CP-L',
 'JNE3613-KR-XXL',
 'SET282-KR-PP-M',
 'JNE3757-KR-XXXL',
 'BL095-M',
 'JNE3776-KR-S',
 'JNE3581-KR-M',
 'J0400-DR-XXXL',
 'J0280-SKD-M',
 'JNE3869-DR-S',
 'JNE3708-TU-S',
 'SET293-KR-NP-XS',
 'JNE3767-KR-XXXL',
 'J0375-SKD-S',
 'J0158-DR-XXXL',
 'SET435-KR-NP-M',
 'JNE3902-KR-L',
 'JNE3363-KR-1032-XL',
 'SET268-KR-NP-M',
 'PJNE3607-KR-5XL',
 'JNE3634-KR-XL',
 'MEN5018-KR-XL',
 'J0230-SKD-XXXL',
 'JNE3620-KR-S',
 'JNE3675-TU-L',
 'JNE3721-KR-S',
 'JNE3160-KR-XXL',
 'J0174-TP-XL',
 'J0331-KR-M',
 'JNE3788-KR-XL',
 'SET139-KR-PP-XXXL',
 'J0395-DR-XS',
 'MEN5009-KR-M',
 'JNE3856-KR-XXXL',
 'JNE3744-TU-XXL',
 'JNE3789-KR-XXXL',
 'SET116-KR-NP-XXXL',
 'BTM026-NP-S',
 'SET332-KR-PP-M',
 'SET257-KR-PP-M',
 'JNE3445-KR-S',
 'SET352-KR-NP-XL',
 'JNE3451-KR-XXL',
 'J0355-KR-XL',
 'JNE3601-KR-S',
 'J0148-SET-L',
 'SET310-KR-NP-XXXL',
 'JNE3575-KR-M',
 'SET376-KR-NP-M',
 'J0301-TP-XL',
 'J0114-TP-XS',
 'JNE3722-KR-M',
 'J0296-DR-S',
 'JNE3695-KR-S',
 'J0100-DR-XXXL',
 'SET293-KR-NP-XXL',
 'JNE3573-KR-XXL',
 'BL073-85BLACK',
 'JNE3553-KR-L',
 'J0374-KR-M',
 'SET409-KR-NP-XS',
 'J0014-LCD-XXXL',
 'J0351-SET-S',
 'JNE3866-KR-XXL',
 'J0108-SKD-XL',
 'SET053-KR-NP-L',
 'AN207-PINK-S',
 'J0150-KR-XXL',
 'JNE3881-DR-XXXL',
 'JNE3284-KR-XXL',
 'J0179-KR-XXXL',
 'J0020-SET-XXXL',
 'JNE2265-KR-501-XXL',
 'J0153-DR-L',
 'JNE3819-KR-M',
 'J0139-KR-M',
 'JNE3612-KR-S',
 'JNE3670-TU-M',
 'SET338-KR-NP-S',
 'J0308-DR-XXXL',
 'JNE3730-KR-L',
 'SET218-KR-NP-S',
 'JNE3821-KR-S',
 'J0301-TP-L',
 'JNE3875-KR-L',
 'JNE3835-KR-M',
 'JNE3774-KR-M',
 'J0278-SET-M',
 'SET073-KR-SHA-XXL',
 'MEN5017-KR-M',
 'J0001-DR-S',
 'J0374-KR-XS',
 'JNE3838-KR-XXL',
 'JNE3773-KR-XXL',
 'J0378-SKD-XL',
 'NW037-TP-SR-S',
 'JNE3875-KR-XXXL',
 'J0008-SKD-XL',
 'SET339-KR-NP-L',
 'JNE3734-KR-XL',
 'BL087-XS',
 'JNE3618-KR-XS',
 'BTM036-PP-L',
 'J0113-TP-S',
 'BTM048-PP-L',
 'J0181-TP-XXXL',
 'NW004-TP-PJ-XL',
 'JNE3791-DR-XS',
 'SET282-KR-PP-L',
 'JNE3689-TU-XXL',
 'JNE3398-KR-S',
 'JNE3465-KR-XS',
 'J0214-TP-L',
 'JNE3555-KR-XXXL',
 'J0072-KR-XL',
 'JNE3608-KR-S',
 'J0295-DR-L',
 'SET038-KR-PP-XXL',
 'SET191-KR-PP-M',
 'JNE3568-KR-XXL',
 'J0420-TP-S',
 'SET233-KR-PP-XXL',
 'JNE3465-KR-XL',
 'SET226-KR-PP-L',
 'JNE3865-TP-XXXL',
 'J0003-SET-XL',
 'J0252-SKD-M',
 'JNE3396-KR-XXXL',
 'NW027-TP-PJ-M',
 'JNE3800-KR-XL',
 'JNE3573-KR-S',
 'J0208-DR-L',
 'JNE3434-KR-XXL',
 'SET376-KR-NP-XL',
 'J0100-DR-S',
 'AN210-NAVY-XL',
 'NW024-TP-PJ-XXL',
 'SET202-KR-NP-M',
 'JNE3760-KR-L',
 'JNE3721-KR-L',
 'J0310-TP-S',
 'JNE3480-KR-L',
 'JNE3401-KR-XXL',
 'JNE3886-KR-XXL',
 'SET408-KR-NP-XS',
 'J0154-DR-XS',
 'J0180-DR-XS',
 'JNE3265-KR-XL',
 'JNE3438-KR-L',
 'JNE3721-KR-XXL',
 'J0083-KR-XS',
 'MEN5016-KR-XXL',
 'JNE3542-KR-M',
 'J0120-TP-XL',
 'SET233-KR-PP-XS',
 'JNE3482-KR-M',
 'SET389-KR-NP-XXXL',
 'JNE3468-KR-XL',
 'JNE3624-KR-L',
 'J0183-TP-XS',
 'JNE3429-KR-XXL',
 'JNE3500-KR-XXL',
 'SET289-KR-NP-L',
 'SET318-KR-SHA-XXXL',
 'J0167-KR-M',
 'NW009-ST-CP-XXL',
 'PJNE3068-KR-5XL',
 'JNE3466-KR-S',
 'JNE3735-KR-L',
 'JNE3366-KR-1053-XXL',
 'JNE3363-KR-1032-XS',
 'SET320-KR-NP-XXL',
 'SAR110',
 'JNE3403-KR-XL',
 'JNE3816-KR-XS',
 'BTM008-XXXL',
 'BL086-XXL',
 'SET403-KR-NP-XXL',
 'J0189-TP-XS',
 'JNE3564-KR-M',
 'J0281-SKD-S',
 'JNE3288-KR-XS',
 'SET355-KR-PP-S',
 'J0346-SET-XS',
 'JNE3615-KR-M',
 'NW028-TP-PJ-M',
 'JNE3833-KR-XS',
 'SET203-KR-DPT-XXXL',
 'J0164-DR-XL',
 'JNE3636-KR-M',
 'J0102-SKD-XL',
 'J0217-BL-M',
 'J0323-CD-S',
 'JNE3610-KR-XXL',
 'J0233-SKD-XXL',
 'J0163-SKD-XXL',
 'J0186-SET-XXL',
 'J0168-DR-M',
 'JNE3727-KR-XXXL',
 'NW006-ST-SR-S',
 'SAR130',
 'SET186-KR-DH-XL',
 'JNE3363-KR-1032-XXL',
 'J0337-TP-XXL',
 'JNE3715-KR-L',
 'JNE3680-TU-S',
 'J0207-DR-XS',
 'JNE3742-KR-L',
 'SET295-KR-NP-S',
 'J0117-TP-XL',
 'JNE3697-KR-XL',
 'JNE3708-TU-XXXL',
 'SET324-KR-NP-M',
 'JNE3619-KR-XS',
 'J0025-DR-M',
 'JNE3434-KR-S',
 'J0338-DR-L',
 'SET378-KR-NP-XXL',
 'JNE3405-KR-S',
 'JNE3435-KR-XXL',
 'JNE3869-DR-XS',
 'SET408-KR-NP-XXL',
 'JNE3621-KR-L',
 'JNE3879-DR-S',
 'J0413-DR-XXL',
 'JNE3719-KR-XS',
 'BL113-L',
 'JNE3560-KR-S',
 'JNE2294-KR-A-XS',
 'J0336-TP-M',
 'JNE3760-KR-XXL',
 'JNE3721-KR-XS',
 'J0284-SKD-L',
 'JNE3437-KR-XXXL',
 'SET340-KR-NP-M',
 'JNE3655-TP-XXL',
 'SET110-KR-PP-XXXL',
 'JNE3703-KR-L',
 'JNE3885-KR-XL',
 'JNE3538-KR-XS',
 'J0344-TP-L',
 'MEN5026-KR-L',
 'AN201-RED-XXL',
 'JNE3447-KR-L',
 'J0332-DR-XXXL',
 'JNE3806-KR-XXL',
 'SET405-KR-NP-XXXL',
 'BL110-M',
 'SET413-KR-NP-M',
 'JNE3544-KR-M',
 'SET321-KR-DPT-XXXL',
 'J0240-SKD-XXXL',
 'JNE3549-KR-XXL',
 'BTM040-PP-S',
 'J0109-SKD-XXL',
 'J0196-TP-XXXL',
 'JNE3767-KR-XS',
 'NW002-TP-PJ-XXL',
 'SET290-KR-DPT-XS',
 'J0194-DR-L',
 'J0075-KR-S',
 'JNE3719-KR-L',
 'JNE3255-KR-M',
 'J0001-DR-XXXL',
 'J0110-SKD-XL',
 'SAR053',
 'SET203-KR-DPT-XXL',
 'SET241-KR-PP-M',
 'SET183-KR-DH-S',
 'SET268-KR-NP-XL',
 'JNE3401-KR-XXXL',
 'SET350-KR-NP-S',
 'J0245-SKD-XXL',
 'NW038-ST-SR-M',
 'SET156-KR-NP-M',
 'JNE3702-KR-M',
 'J0402-DR-XS',
 'JNE3394-KR-M',
 'J0279-SET-S',
 'JNE3807-KR-XXL',
 'SET365-KR-NP-XL',
 'JNE3460-KR-XXL',
 'JNE3252-KR-XS',
 'SET246-KR-PP-S',
 'J0280-SKD-XL',
 'SET318-KR-SHA-S',
 'SET138-KR-PP-S',
 'NW038-ST-SR-XL',
 'SET197-KR-NP-M',
 'JNE3614-KR-L',
 'JNE3736-KR-XXXL',
 'JNE3894-TP-M',
 'J0283-SET-XXL',
 'SET332-KR-PP-XL',
 'SET385-KR-NP-XS',
 'JNE3575-KR-XXL',
 'JNE3655-TP-S',
 'JNE3637-KR-S',
 'JNE3484-KR-XXL',
 'J0213-TP-XS',
 'JNE3655-TP-XL',
 'J0192-TP-S',
 'JNE3836-KR-S',
 'J0375-SKD-XXL',
 'AN204-PURPLE-XL',
 'J0401-DR-XS',
 'J0416-DR-M',
 'BTM032-NP-S',
 'SET062-KR-SP-XXXL',
 'SET393-KR-NP-XXXL',
 'J0179-KR-XL',
 'JNE3745-KR-XL',
 'J0161-DR-L',
 'JNE3456-KR-M',
 'NW030-TP-PJ-XXL',
 'SET442-KR-NP-M',
 'JNE3773-KR-L',
 'SET415-KR-NP-XXL',
 'J0348-SET-XL',
 'SET263-KR-NP-XS',
 'SET339-KR-NP-XL',
 'SET270-KR-PP-XXL',
 'SET337-KR-NP-XL',
 'JNE3515-KR-M',
 'SET319-KR-NP-XL',
 'JNE3621-KR-XL',
 'J0161-DR-XXXL',
 'SET187-KR-DH-XL',
 'SET230-KR-PP-L',
 'SET325-KR-NP-XS',
 'J0296-DR-XXL',
 'JNE3790-KR-XL',
 'J0095-SET-L',
 'SET285-KR-SHA-S',
 'SET289-KR-NP-XL',
 'J0057-DR-S',
 'J0190-TP-L',
 'J0293-DR-XXL',
 'NW002-TP-PJ-XXXL',
 'JNE3413-KR-L',
 'J0205-TP-XXXL',
 'J0204-TP-XXL',
 'JNE3749-KR-L',
 'BTM041-PP-XL',
 'JNE3468-KR-XXL',
 'JNE1408-GREY-KR-UDF19-XXXL',
 'SET253-KR-NP-XXL',
 'SET404-KR-NP-XL',
 'J0236-SKD-XXXL',
 'J0151-KR-L',
 'J0204-TP-XXXL',
 'J0228-SKD-XXXL',
 'JNE2171-KR-437-XS',
 'SET345-KR-NP-M',
 'J0305-DR-M',
 'J0324-CD-L',
 'J0229-SKD-XL',
 'SET276-KR-PP-XXXL',
 'J0236-SKD-L',
 'MEN5032-KR-XXL',
 'NW013-ST-SR-S',
 'J0013-SKD-M',
 'J0183-TP-XL',
 'J0164-DR-L',
 'SET319-KR-NP-XXXL',
 'SET327-KR-DPT-XS',
 'SET415-KR-NP-XXXL',
 'J0396-DR-S',
 'J0003-SET-XXL',
 'JNE1525-KR-UDF19BLACK-S',
 'J0088-TP-XS',
 'JNE3761-KR-S',
 'JNE3500-KR-M',
 'SET373-KR-PP-XXL',
 'J0082-TP-L',
 'BL111-S',
 'JNE3256-KR-XS',
 'SET326-KR-PP-XS',
 'SAR135',
 'SET364-KR-NP-XXXL',
 'SET369-KR-NP-XXXL',
 'JNE3434-KR-M',
 'JNE2307-KR-572-XXL',
 'JNE3818-KR-XXXL',
 'JNE2131-KR-A-S',
 'JNE3766-KR-M',
 'JNE3557-KR-XXL',
 'JNE3524-KR-L',
 'SET317-KR-PP-XS',
 'JNE3557-KR-S',
 'JNE1234-MULTI-KR-032-M',
 'JNE3396-KR-XXL',
 'SET199-KR-NP-XXL',
 'J0370-SKD-L',
 'SET073-KR-SHA-S',
 'JNE3683-TU-XS',
 'JNE3738-KR-XXL',
 'JNE3225-KR-L',
 'SET333-KR-DPT-XXL',
 'SET224-KR-NP-XS',
 'JNE3706-DR-M',
 'J0097-KR-XS',
 'JNE3749-KR-XS',
 'J0341-DR-M',
 'JNE3261-KR-XXL',
 'NW028-TP-PJ-XL',
 'SET075-KR-DH-L',
 'JNE3615-KR-L',
 'MEN5014-KR-M',
 'J0332-DR-S',
 'J0039-SET-S',
 'JNE3548-KR-S',
 'J0185-DR-S',
 'J0209-DR-XXXL',
 'J0122-TP-XS',
 'JNE3628-KR-L',
 'JNE3770-KR-L',
 'SAR140',
 'SET225-KR-NP-M',
 'JNE3460-KR-XL',
 'JNE3265-KR-S',
 'NW014-ST-SR-M',
 'JNE3484-KR-L',
 'J0339-DR-M',
 'JNE3774-KR-XL',
 'SAR096',
 'J0349-SET-M',
 'SAR070',
 'JNE3752-KR-XL',
 'NW004-TP-PJ-M',
 'JNE3553-KR-XXXL',
 'JNE3866-KR-S',
 'SET073-KR-SHA-M',
 'J0131-KR-XS',
 'J0220-BL-L',
 'J0308-DR-L',
 'J0091-TP-XXXL',
 'SET226-KR-PP-S',
 'J0096-KR-S',
 'JNE3407-KR-L',
 'JNE3735-KR-M',
 'SET204-KR-DPT-XS',
 'JNE3160-KR-S',
 'SET363-KR-NP-XXL',
 'NW031-TP-PJ-S',
 'SET366-KR-NP-XXL',
 'BL100-S',
 'JNE3616-KR-XXL',
 'J0167-KR-XXL',
 'J0197-TP-S',
 'JNE3528-KR-XXXL',
 'J0122-TP-M',
 'SET037-KR-NP-XL',
 'SET279-LC-XS',
 'JNE3391-KR-M',
 'SET270-KR-PP-M',
 'J0370-SKD-XXXL',
 'SET366-KR-NP-M',
 'SET315-KR-PP-XXXL',
 'JNE3790-KR-XXL',
 'JNE3386-KR-XS',
 'SET347-KR-NP-L',
 'SET048-KR-NP-L',
 'JNE2251-KR-537-L',
 'JNE3806-KR-XL',
 'SET333-KR-DPT-XS',
 'J0277-SKD-L',
 'SET306-KR-PP-XS',
 'J0216-BL-L',
 'SET275-KR-NP-XL',
 'J0314-KR-L',
 'J0149-KR-XS',
 'SET300-KR-NP-M',
 'JNE3890-TP-S',
 'JNE3431-KR-XL',
 'JNE3473-KR-XXL',
 'J0226-SKD-XL',
 'J0415-DR-M',
 'J0124-TP-XS',
 'JNE3880-DR-M',
 'J0131-KR-XXL',
 'JNE3756-KR-XXXL',
 'JNE3413-KR-M',
 'SET100-KR-PP-XS',
 'SET359-KR-NP-XXL',
 'J0153-DR-M',
 'JNE3468-KR-XXXL',
 'J0005-DR-L',
 'SET087-KR-PP-S',
 'NW007-ST-CP-XL',
 'AN202-ORANGE-S',
 'MEN5011-KR-L',
 'SET138-KR-PP-L',
 'SET363-KR-NP-L',
 'J0371-SKD-XL',
 'SET415-KR-NP-XL',
 'JNE3878-KR-XXXL',
 'PSET058-KR-NP-5XL',
 'JNE3455-KR-XXXL',
 'SET386-KR-NP-M',
 'SET444-KR-SH-XXXL',
 'J0379-SKD-M',
 'J0283-SET-L',
 'SET244-KR-NP-XXXL',
 'JNE3865-TP-XL',
 'J0161-DR-M',
 'JNE3720-KR-XXXL',
 'JNE2305-KR-533-S',
 'SET375-KR-NP-XXXL',
 'SET186-KR-DH-XS',
 'JNE3800-KR-XS',
 'NW036-ST-SR-S',
 'JNE2100-KR-144-XXXL',
 'J0173-DR-XL',
 'SET144-KR-NP-XXL',
 'SET179-KR-PP-XXL',
 'J0077-SKD-XL',
 'JNE3405-KR-XXXL',
 'J0117-TP-XXXL',
 'JNE3610-KR-XS',
 'J0026-KR-XS',
 'JNE3160-KR-M',
 'NW009-ST-CP-XL',
 'SET364-KR-NP-L',
 'JNE3864-TU-S',
 'JNE1977-KR-237-XXL',
 'J0299-KR-S',
 'JNE3485-KR-XS',
 'JNE3391-KR-XXL',
 'J0165-TP-XS',
 'JNE3770-KR-XS',
 'J0079-SKD-XXXL',
 'SET097-KR-PP-XL',
 'J0238-LCD-XL',
 'JNE3728-KR-L',
 'J0036-TP-XS',
 'JNE3690-TU-XL',
 'SET316-KR-DPT-XXL',
 'J0295-DR-S',
 'SET307-KR-DPT-XXXL',
 'SET366-KR-NP-L',
 'SET110-KR-PP-L',
 'J0158-DR-S',
 'JNE3778-KR-L',
 'JNE3488-KR-XS',
 'MEN5027-KR-XXL',
 'JNE3691-TU-XS',
 'J0331-KR-S',
 'JNE3476-KR-XXL',
 'SET263-KR-NP-XL',
 'JNE3881-DR-S',
 'J0350-SET-XL',
 'JNE3805-KR-XXXL',
 'BL099-L',
 'SET313-KR-NP-S',
 'SET320-KR-NP-XL',
 'MEN5025-KR-M',
 'SET290-KR-DPT-L',
 'SET409-KR-NP-M',
 'SET299-KR-PP-XXXL',
 'SET409-KR-NP-XL',
 'J0217-BL-L',
 'JNE3799-KR-XL',
 'JNE3890-TP-XXL',
 'SET374-KR-NP-XS',
 'JNE3905-DR-XXL',
 'JNE3879-DR-L',
 'SET219-KR-PP-XXXL',
 'J0400-DR-L',
 'SET232-KR-PP-S',
 'J0111-TP-L',
 'JNE3684-TU-XL',
 'J0118-TP-XXL',
 'JNE3791-DR-S',
 'JNE3928-KR-XXXL',
 'JNE3065-KR-XXL',
 'J0159-DR-XS',
 'JNE3313-KR-XL',
 'JNE3897-KR-XXXL',
 'JNE3706-DR-XS',
 'J0195-TP-XXL',
 'SET229-KR-PP-XXL',
 'SET376-KR-NP-S',
 'JNE3609-KR-L',
 'SET435-KR-NP-L',
 'SET307-KR-DPT-M',
 'NW004-TP-PJ-XXXL',
 'JNE3807-KR-XL',
 'MEN5016-KR-XXXL',
 'J0250-SKD-XXXL',
 'JNE3902-KR-M',
 'JNE3700-KR-L',
 'J0396-DR-XXL',
 'SET038-KR-PP-XXXL',
 'JNE3618-KR-XL',
 'SET343-KR-NP-S',
 'SET316-KR-DPT-M',
 'JNE3609-KR-XS',
 'SAR108',
 'J0181-TP-XXL',
 'SAR137',
 'JNE3602-KR-L',
 'J0290-CD-S',
 'BL110-S',
 'J0431-DR-XXL',
 'J0112-TP-XS',
 'JNE3905-DR-L',
 'SET246-KR-PP-M',
 'JNE3890-TP-XL',
 'J0210-DR-S',
 'SET303-KR-NP-XXL',
 'J0398-DR-XXL',
 'JNE3485-KR-XL',
 'J0207-DR-XL',
 'SET383-KR-NP-XL',
 'J0418-TP-XL',
 'J0212-DR-L',
 'JNE3579-KR-XXL',
 'J0034-SET-M',
 'JNE3704-KR-XXL',
 'JNE3780-KR-S',
 'J0431-DR-XL',
 'JNE3801-KR-XXXL',
 'SET289-KR-NP-M',
 'AN201-RED-XL',
 'NW038-ST-SR-XS',
 'JNE3795-KR-M',
 'SET070-KR-NP-XS',
 'JNE3614-KR-S',
 'JNE3463-KR-XXL',
 'JNE3404-KR-XL',
 'J0093-DR-L',
 'JNE3601-KR-XXL',
 'NW034-TP-PJ-S',
 'J0335-DR-XL',
 'J0110-SKD-XXL',
 'JNE3398-KR-XL',
 'JNE3288-KR-S',
 'JNE3768-KR-XL',
 'JNE3714-KR-S',
 'SET384-KR-NP-S',
 'CH205-YELLOW-XXL',
 'BTM039-PP-XS',
 'J0382-SKD-XXL',
 'JNE3635-KR-S',
 'JNE3638-KR-M',
 'JNE3793-KR-XS',
 'J0338-DR-XS',
 'MEN5021-KR-XXXL',
 'SET223-KR-NP-XXL',
 'SET390-KR-NP-XS',
 'JNE3688-TU-L',
 'JNE3825-KR-XXL',
 'J0078-SET-M',
 'J0166-DR-S',
 'JNE3435-KR-S',
 'NW035-ST-CP-S',
 'JNE3571-KR-XL',
 'J0300-TP-L',
 'JNE3732-KR-XXXL',
 'JNE3543-KR-XXXL',
 'MEN5012-KR-L',
 'NW034-TP-PJ-XS',
 'J0005-DR-M',
 'JNE3439-KR-XXL',
 'JNE3636-KR-XS',
 'JNE3763-KR-XL',
 'J0179-KR-M',
 'SET197-KR-NP-L',
 'J0416-DR-L',
 'SET254-KR-NP-L',
 'JNE3902-KR-XXXL',
 'SET380-KR-NP-XL',
 'J0119-TP-XS',
 'J0062-DR-S',
 'JNE3566-KR-XXL',
 'J0141-KR-XXL',
 'NW020-ST-SR-XL',
 'SET244-KR-NP-XS',
 'JNE3567-KR-L',
 'JNE3408-KR-XS',
 'SET343-KR-NP-XXL',
 'JNE3804-KR-L',
 'J0094-KR-XXXL',
 'J0343-DR-XXXL',
 'PJNE3068-KR-6XL',
 'MEN5027-KR-S',
 'J0049-TP-L',
 'AN212-WHITE-M',
 'J0306-DR-XS',
 'MEN5003-KR-XXL',
 'SET388-KR-NP-XXXL',
 'JNE3560-KR-XL',
 'JNE3720-KR-L',
 'J0043-SET-XL',
 'SET147-KR-NP-XL',
 'J0236-SKD-XXL',
 'SET343-KR-NP-XL',
 'SET380-KR-NP-XXXL',
 'NW005-ST-PJ-L',
 'J0431-DR-XS',
 'SET153-KR-NP-XS',
 'PJNE3068-KR-4XL',
 'JNE3864-TU-XL',
 'NW002-TP-PJ-L',
 'J0397-DR-XXL',
 'SET251-KR-PP-XXXL',
 'AN205-YELLOW-XL',
 'J0178-TP-XXXL',
 'J0341-DR-XXXL',
 'JNE3468-KR-L',
 'J0240-SKD-XS',
 'JNE3756-KR-XXL',
 'JNE3861-DR-L',
 'J0277-SKD-XXXL',
 'JNE3483-KR-XXXL',
 'JNE3506-KR-L',
 'J0248-KR-DPT-L',
 'JNE3403-KR-M',
 'J0122-TP-S',
 'JNE3359-KR-L',
 'J0298-DR-XS',
 'J0105-KR-XXL',
 'JNE3897-KR-XL',
 'BL003-50BLACK',
 'JNE3730-KR-S',
 'JNE3689-TU-XXXL',
 'J0142-KR-XS',
 'J0163-SKD-XS',
 'JNE3485-KR-M',
 'J0414-DR-S',
 'JNE3432-KR-XL',
 'SET438-KR-NP-XL',
 'JNE3273-KR-L',
 'NW015-TP-PJ-M',
 'BTM027-NP-L',
 'NW032-ST-CP-L',
 'JNE3451-KR-M',
 'J0337-TP-XS',
 'J0145-SET-XXXL',
 'SET276-KR-PP-XXL',
 'JNE3579-KR-XL',
 'JNE3837-KR-XXXL',
 'J0283-SET-S',
 'SET247-KR-SHA-XXXL',
 'SET238-KR-PP-M',
 'J0101-DR-XXL',
 'JNE3670-TU-XL',
 'BL104-XL',
 'JNE3491-KR-XS',
 'SET278-KR-NP-L',
 'JNE3400-KR-XS',
 'JNE3371-KR-XXXL',
 'NW031-TP-PJ-XS',
 'JNE3429-KR-M',
 'JNE3891-TP-XXL',
 'J0310-TP-XL',
 'J0159-DR-M',
 'J0081-DR-L',
 'JNE3451-KR-L',
 'JNE3833-KR-XL',
 'SAR154',
 'JNE3609-KR-XL',
 'J0092-SET-S',
 'J0398-DR-XS',
 'SET385-KR-NP-XXL',
 'JNE3825-KR-M',
 'J0382-SKD-XXXL',
 'JNE3602-KR-XS',
 'J0155-KR-XL',
 'J0135-SET-XXXL',
 'JNE3890-TP-XXXL',
 'J0185-DR-M',
 'SET350-KR-NP-XXXL',
 'JNE3789-KR-XXL',
 'J0231-SKD-XXL',
 'SET116-KR-NP-S',
 'J0041-SET-M',
 'JNE3472-KR-S',
 'JNE3614-KR-XXXL',
 'J0140-SET-M',
 'JNE3670-TU-XXL',
 'SET269-KR-NP-M',
 'J0278-SET-XXL',
 'SET251-KR-PP-XS',
 'JNE3729-KR-S',
 'NW033-ST-CP-S',
 'JNE3562-KR-M',
 'SAR173',
 'SAR037',
 'JNE3690-TU-XXL',
 'JNE3482-KR-L',
 'SET377-KR-NP-L',
 'SET305-KR-DPT-XXL',
 'JNE3261-KR-M',
 'JNE3783-KR-XXL',
 'SET188-KR-NP-L',
 'SET252-KR-PP-XS',
 'J0220-BL-XL',
 'NW014-ST-SR-L',
 'J0310-TP-XXL',
 'JNE3760-KR-S',
 'SET384-KR-NP-L',
 'JNE3613-KR-S',
 'JNE3412-KR-L',
 'MEN5024-KR-L',
 'JNE3547-KR-XXL',
 'J0140-SET-L',
 'JNE3738-KR-M',
 'SET347-KR-NP-XXXL',
 'J0417-TP-XS',
 'SET316-KR-DPT-S',
 'J0314-KR-S',
 'JNE3313-KR-M',
 'JNE3720-KR-XL',
 'SAR051',
 'JNE3756-KR-L',
 'JNE3704-KR-XL',
 'JNE3483-KR-XXL',
 'JNE3722-KR-L',
 'J0240-SKD-S',
 'MEN5001-KR-L',
 'SET267-KR-NP-S',
 'JNE3633-KR-S',
 'JNE3767-KR-XXL',
 'BTM039-PP-L',
 'SET171-KR-NP-XL',
 'J0104-KR-S',
 'JNE3368-KR-XXXL',
 'JNE3743-TP-L',
 'J0048-TP-S',
 'JNE3548-KR-M',
 'SET203-KR-DPT-L',
 'J0184-KR-M',
 'BTM008-XXL',
 'J0390-TP-S',
 'JNE3810-KR-XXL',
 'SET313-KR-NP-XL',
 'MEN5013-KR-M',
 'JNE3803-KR-XL',
 'SET252-KR-PP-M',
 'SAR030',
 'J0372-SKD-XXL',
 'JNE3518-KR-XXL',
 'BL075-85CHIKU',
 'BTM035-NP-XS',
 'SET184-KR-PP-XS',
 'JNE3261-KR-XS',
 'SET302-KR-PP-XXXL',
 'SET245-KR-NP-S',
 'JNE3743-TP-M',
 'JNE3865-TP-L',
 'MEN5023-KR-S',
 'J0180-DR-XXXL',
 'JNE3602-KR-M',
 'JNE1998-KR-311-S',
 'J0153-DR-XS',
 'JNE3485-KR-XXL',
 'JNE3655-TP-XS',
 'JNE3443-KR-XS',
 'MEN5024-KR-S',
 'JNE3391-KR-S',
 'JNE3881-DR-XXL',
 'J0162-SKD-L',
 'J0381-SKD-XL',
 'JNE3459-KR-XXXL',
 'SET055-KR-NP-XS',
 'JNE3624-KR-XL',
 'J0147-SET-L',
 'MEN5025-KR-XL',
 'SET339-KR-NP-XXXL',
 'SET165-KR-PP-XL',
 'JNE3905-DR-S',
 'JNE3669-TU-XL',
 'J0132-KR-XS',
 'BL103-M',
 'JNE3564-KR-XXXL',
 'JNE3459-KR-S',
 'JNE3837-KR-XL',
 'JNE3541-KR-S',
 'SET317-KR-PP-M',
 'MEN5015-KR-L',
 'JNE3795-KR-S',
 'JNE3618-KR-S',
 'J0108-SKD-XS',
 'J0201-TP-S',
 'JNE3568-KR-S',
 'BTM043-PP-S',
 'AN205-YELLOW-S',
 'J0198-TP-M',
 ...}

In [20]:
len(
    set(df['SKU']).intersection(
        set(sale_report['SKU Code'])
    )
)

6617

In [21]:
df['SKU'].nunique()

7195

In [22]:
sale_report['SKU Code'].nunique()

9170

In [23]:
round(
    len(set(df['SKU']).intersection(set(sale_report['SKU Code'])))
    *100
    / df['SKU'].nunique(),
    2
)

91.97

Data Cleaning for Sales report table

In [24]:
sale_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9271 entries, 0 to 9270
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9271 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9235 non-null   object
 3   Stock       9235 non-null   float64
 4   Category    9226 non-null   object
 5   Size        9235 non-null   object
 6   Color       9226 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 507.1+ KB

In [25]:
sale_report.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [26]:
sale_report.duplicated().sum()

np.int64(0)

In [27]:
sale_report_clean = sale_report.dropna()

In [28]:
sale_report_clean.isnull().sum()

index         0
SKU Code      0
Design No.    0
Stock         0
Category      0
Size          0
Color         0
dtype: int64

In [29]:
sale_report_clean.shape

(9188, 7)

In [30]:
sale_report_clean.to_csv(
    "Cleaned data/clean_sale_report.csv",
    index=False
)